version: '3.8'

services:
  nginx:
    image: nginx:1.25
    ports:
      - ${DOCKER_API_PORT}:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./app:/app
      - ./docker/swagger/openapi.yml.php:/swagger/openapi.yml.php
      - composer:/root/.composer/cache
    env_file:
      - ./.env

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON_URL=//${DOCKER_SWAGGER_SERVER}/openapi.yml
    ports:
      - ${DOCKER_SWAGGER_PORT}:8080

volumes:
  composer:
